/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author Kajay PC
 */
public class FormObat extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model;

    /**
     * Creates new form FormObat
     */
    public FormObat() {
        initComponents();
        conn = new Koneksi().getKoneksi();
    }
private void kosong() {

    txtkode.setText("");
    txtNama.setText("");
    txtjenis.setText("");
    txtstok.setText("");
    txtharga.setText("");
    
    txtkode.requestFocus();

    }
 private void tampilData(){

    model = new DefaultTableModel();

    model.addColumn("Kode Obat");
    model.addColumn("Nama Obat");
    model.addColumn("Jenis Obat");
    model.addColumn("Stok Obat");
    model.addColumn("Harga Obat");

    try{

        String sql = "SELECT * FROM obat";

        pst = conn.prepareStatement(sql);

        rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("kode_Obat"),
                rs.getString("nama_Obat"),
                rs.getString("jenis"),
                rs.getInt("stok"),
                rs.getDouble("harga")

            });

        }

        tblObat.setModel(model);

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }

}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        btnsiman = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Obat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));

        jLabel2.setText("Kode Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 36, 85, -1));

        jLabel3.setText("Nama Obat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 67, 85, -1));

        jLabel4.setText("Jenis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 98, 85, -1));

        jLabel5.setText("Stok");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 129, 85, -1));

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 160, 85, -1));

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode_obat", "nama_obat", "jenis", "stok", "harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 191, 375, 122));

        btnsiman.setText("Simpan");
        btnsiman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsiman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, -1, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 345, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 345, -1, -1));

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 345, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 345, -1, -1));

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 345, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
 try{

    String sql="SELECT * FROM obat WHERE kode_obat=?";

    pst=conn.prepareStatement(sql);

    pst.setString(1,txtkode.getText());

    rs=pst.executeQuery();

    if(rs.next()){

        txtNama.setText(rs.getString("nama_obat"));
        txtjenis.setText(rs.getString("jenis"));
        txtstok.setText(rs.getString("stok"));
        txtharga.setText(rs.getString("harga"));

    }else{

        JOptionPane.showMessageDialog(null,"Data Tidak Ditemukan");

    }

}catch(Exception e){

    JOptionPane.showMessageDialog(null,e);

}         // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
    new MenuUtama().setVisible(true);
    dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tblObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObatMouseClicked
int baris = tblObat.getSelectedRow();

txtkode.setText(model.getValueAt(baris,0).toString());

txtNama.setText(model.getValueAt(baris,1).toString());

txtjenis.setText(model.getValueAt(baris,2).toString());

txtstok.setText(model.getValueAt(baris,3).toString());

txtharga.setText(model.getValueAt(baris,4).toString());         // TODO add your handling code here:
    }//GEN-LAST:event_tblObatMouseClicked

    private void btnsimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimanActionPerformed
try{

    String sql = "INSERT INTO obat VALUES(?,?,?,?,?)";

    pst = conn.prepareStatement(sql);

    pst.setString(1, txtkode.getText());
    pst.setString(2, txtNama.getText());
    pst.setString(3, txtjenis.getText());
    pst.setString(4, txtstok.getText());
    pst.setString(5, txtharga.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");

    tampilData();

    kosong();

}catch(Exception e){

    JOptionPane.showMessageDialog(null,e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
 try{

        String sql = "UPDATE obat SET "
                + "nama_obat=?,"
                + "jenis=?,"
                + "stok=?,"
                + "harga=? "
                + "WHERE kode_obat=?";

        pst = conn.prepareStatement(sql);

        pst.setString(1, txtNama.getText());
        pst.setString(2, txtjenis.getText());
        pst.setString(3, txtstok.getText());
        pst.setString(4, txtharga.getText());
        pst.setString(5, txtkode.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null,"Data berhasil diubah");

        tampilData();
        kosong();

    }catch(Exception e){

        JOptionPane.showMessageDialog(null,e);

    }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
try{

    String sql="DELETE FROM obat WHERE kode_obat=?";

    pst=conn.prepareStatement(sql);

    pst.setString(1,txtkode.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");

    tampilData();

    kosong();

}catch(Exception e){

    JOptionPane.showMessageDialog(null,e);

}         // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
kosong();
tampilData();         // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsiman;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblObat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
