/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Kajay PC
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuBar2 = new javax.swing.JMenuBar();
        Laporan = new javax.swing.JMenu();
        mnDokter = new javax.swing.JMenuItem();
        mnPasien = new javax.swing.JMenuItem();
        mnObat = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuDokter = new javax.swing.JMenuItem();
        menuPasien = new javax.swing.JMenuItem();
        MenuObat = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        lapDokter = new javax.swing.JMenuItem();
        lapPasien = new javax.swing.JMenuItem();
        lapObat = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        Laporan.setText("Master");

        mnDokter.setText("Data Dokter");
        mnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDokterActionPerformed(evt);
            }
        });
        Laporan.add(mnDokter);

        mnPasien.setText("Data Pasien");
        mnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPasienActionPerformed(evt);
            }
        });
        Laporan.add(mnPasien);

        mnObat.setText("Data Obat");
        mnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnObatActionPerformed(evt);
            }
        });
        Laporan.add(mnObat);

        jMenuBar2.add(Laporan);
        jMenuBar2.add(Keluar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Rumah Sakit");
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistem Informasi Rumah Sakit");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${font}"), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("font"));
        bindingGroup.addBinding(binding);

        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Aplikasi Pengolahan Data Dokter, Pasien dan Obat");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Selamat Datang Di Aplikasi ");

        menuMaster.setText("Master");

        menuDokter.setText("Data Dokter");
        menuDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDokterActionPerformed(evt);
            }
        });
        menuMaster.add(menuDokter);

        menuPasien.setText("Data Pasien");
        menuPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPasienActionPerformed(evt);
            }
        });
        menuMaster.add(menuPasien);

        MenuObat.setText("Data Obat");
        MenuObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuObatActionPerformed(evt);
            }
        });
        menuMaster.add(MenuObat);

        jMenuBar1.add(menuMaster);

        menuLaporan.setText("Laporan");

        lapDokter.setText("Laporan Dokter");
        lapDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapDokterActionPerformed(evt);
            }
        });
        menuLaporan.add(lapDokter);

        lapPasien.setText("Laporan Pasien");
        lapPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPasienActionPerformed(evt);
            }
        });
        menuLaporan.add(lapPasien);

        lapObat.setText("Laporan Obat");
        lapObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapObatActionPerformed(evt);
            }
        });
        menuLaporan.add(lapObat);

        jMenuBar1.add(menuLaporan);

        menuKeluar.setText("Keluar");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuKeluar.add(menuExit);

        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDokterActionPerformed
FormDokter dokter = new FormDokter();

dokter.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuDokterActionPerformed

    private void menuPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPasienActionPerformed
   FormPasien pasien = new FormPasien();

    pasien.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_menuPasienActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
int jawab = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin keluar?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION);

if (jawab == JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void lapObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapObatActionPerformed
try {

        Connection conn = new Koneksi().getKoneksi();

        JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/report/obat.jasper"),
                null,
                conn);

        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Laporan gagal ditampilkan!\n" + e.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_lapObatActionPerformed

    private void MenuObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuObatActionPerformed
    FormObat obat = new FormObat();

    obat.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_MenuObatActionPerformed

    private void mnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPasienActionPerformed

    private void mnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnObatActionPerformed

    private void lapDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapDokterActionPerformed
     try {

        Connection conn = new Koneksi().getKoneksi();

        JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/report/dokter.jasper"),
                null,
                conn);

        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Laporan gagal ditampilkan!\n" + e.getMessage());

    }    // TODO add your handling code here:
    }//GEN-LAST:event_lapDokterActionPerformed

    private void mnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnDokterActionPerformed

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentHidden

    private void lapPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPasienActionPerformed
try {

        Connection conn = new Koneksi().getKoneksi();

        JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/report/pasien.jasper"),
                null,
                conn);

        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Laporan gagal ditampilkan!\n" + e.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_lapPasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Keluar;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem MenuObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem lapDokter;
    private javax.swing.JMenuItem lapObat;
    private javax.swing.JMenuItem lapPasien;
    private javax.swing.JMenuItem menuDokter;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPasien;
    private javax.swing.JMenuItem mnDokter;
    private javax.swing.JMenuItem mnObat;
    private javax.swing.JMenuItem mnPasien;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
